### ISSUE TITLE
Add embedded example

### ISSUE THREAD

**Issue by bookercodes** [nsebhastian/react-chatbox-component#3]
This issue is dependent on #2.

Once #2 is complete, we can create a new example: `examples/embedded` to show how to use the `ChatBox` component to create an embedded chat:

![image](https://user-images.githubusercontent.com/11927968/66997330-2701cc00-f0ca-11e9-941c-035955e13622.png)

I imagine the example code will look _something_ like this:

```
const embeddedChatContainerStyle = {
  // horizontally centre the chat container (I wish CSS was really this easy haha)
}

<div style={{embeddedChatContainerStyle}}>
  <heading>
     <h1>Embedded chat</h1>
  </heading>
  <ChatBox />
</div>
```

**Comment by nsebhastian** [comment]
https://github.com/nsebhastian/react-chatbox-component/commit/9c58ad44bd87bb6e1c8a9bff95e480f532578926
