### ISSUE TITLE
Populate examples with sample messages

### ISSUE THREAD

**Issue by bookercodes** [nsebhastian/react-chatbox-component#4]
How I would do it:

Create a function like

```
const fetchHistoricalMessags = () => {
   // here I hard-coded some test messages. realistically you will fetch these messages from your chat server like CometChat
   return [ 
    { text: "message 1", ... },
    { text: "message 2", ... },
   ]
}
```

The aim here is twofold:

* Having some test messages makes the app a bit more interesting
* Creating a function like this makes it really obvious where you need to go and write your own logic. Ideally, with CometChat. Your tutorial can use the same function to create even more consistency :)

**Comment by nsebhastian** [comment]
https://github.com/nsebhastian/react-chatbox-component/commit/9c58ad44bd87bb6e1c8a9bff95e480f532578926
